# Generated by Django 3.1.3 on 2020-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlem', models.FloatField()),
                ('boylam', models.FloatField()),
                ('sorun', models.CharField(max_length=50)),
                ('ana_unsur', models.CharField(max_length=50)),
                ('benzerlik', models.CharField(max_length=50)),
                ('alinabilecek_onlem', models.TextField()),
                ('kayıt_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
