# Generated by Django 3.1.3 on 2020-11-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0002_anket_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anket',
            name='kayıt_tarihi',
        ),
    ]
