# Generated by Django 3.1.3 on 2020-11-14 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anket', '0003_remove_anket_kayıt_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='anket',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='anket',
            name='alinabilecek_onlem',
            field=models.TextField(verbose_name='Sorun ve Çözüm İçin Tavsiyeler'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='ana_unsur',
            field=models.CharField(max_length=50, verbose_name='Sorun Kim Tarafından Kaynaklı'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kayıdı oluşturan'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='benzerlik',
            field=models.CharField(max_length=50, verbose_name='Hangi Guruba Dahil'),
        ),
    ]
