# Generated by Django 3.1.3 on 2020-11-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0004_auto_20201115_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deneme',
        ),
    ]
