# Generated by Django 3.1.3 on 2020-12-04 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anket', '0005_delete_deneme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Kayıdı oluşturan'),
        ),
    ]
