# Generated by Django 3.1.3 on 2020-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0011_auto_20201213_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='alinabilecek_onlem',
            field=models.TextField(blank=True, verbose_name='Sorun ve Çözüm İçin Tavsiyeler'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='boylam',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anket',
            name='enlem',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
