# Generated by Django 3.1.3 on 2020-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0012_auto_20201219_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='boylam',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anket',
            name='enlem',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
