# Generated by Django 3.1.3 on 2020-12-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0013_auto_20201219_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='boylam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anket',
            name='enlem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
